apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg-alone
  namespace: demo
spec:
  version: "8.0.17"
  podTemplate:
    spec:
      containers:
        - name: mongodb
          resources:
            requests:
              cpu: "300m"
              memory: "400Mi"
  storage:
    resources:
      requests:
        storage: 500Mi
    storageClassName: standard
  deletionPolicy: WipeOut
