apiVersion: kubedb.com/v1alpha2
kind: Hazelcast
metadata:
  name: hz-grafana-demo
  namespace: demo
spec:
  version: "5.5.6"
  replicas: 3
  licenseSecret:
    name: hz-license-key
  deletionPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
