apiVersion: kubedb.com/v1alpha2
kind: Solr
metadata:
  name: solr-alert
  namespace: alert-solr
spec:
  version: "9.8.0"
  replicas: 3
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
  solrModules:
  - s3-repository
  - gcs-repository
  - prometheus-exporter
  zookeeperRef:
    name: zoo
    namespace: alert-solr
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
  deletionPolicy: WipeOut
