apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg-standalone
  namespace: demo
spec:
  version: "7.0.28"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi