apiVersion: kubedb.com/v1alpha2
kind: RabbitMQ
metadata:
  name: rmq-alert-demo
  namespace: alert-rabbitmq
spec:
  version: "4.0.4"
  replicas: 1
  deletionPolicy: WipeOut
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        interval: 10s
        labels:
          release: prometheus
