apiVersion: ops.kubedb.com/v1alpha1
kind: DocumentDBOpsRequest
metadata:
  name: documentdb-cls-hscale-up
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: documentdb-cls-sample
  horizontalScaling:
    replicas: 5
