apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: qdrant-addon
spec:
  backupTasks:
  - name: logical-backup
    function: qdrant-backup
    driver: Restic
    executor: Job
    singleton: true
    parameters:
    - name: collections
      usage: Comma-separated list of collections to backup. If not specified, all collections will be backed up.
      required: false
    - name: args
      usage: Arguments to be passed to the dump command.
      required: false
    - name: enableCache
      usage: Enable or disable caching. Disabling caching may impact backup performance.
      required: false
      default: "true"
    - name: scratchDir
      usage: Directory for holding temporary files and restic cache.
      required: false
      default: /kubestash-tmp
    volumeTemplate:
    - name: kubestash-tmp-volume
      usage: Holds temporary files and restic cache.
      source:
        emptyDir: {}
    volumeMounts:
    - name: kubestash-tmp-volume
      mountPath: /kubestash-tmp
  - name: volume-snapshot
    function: qdrant-csi-snapshotter
    driver: VolumeSnapshotter
    executor: Job
    singleton: true
    parameters:
      - name: volumeSnapshotClassName
        usage: The VolumeSnapshotClassName to be used by volumeSnapshot
        required: false      
  - name: manifest-backup
    function: kubedbmanifest-backup
    driver: Restic
    executor: Job
    singleton: true
    parameters:
    - name: enableCache
      usage: Enable or disable caching. Disabling caching may impact backup performance.
      required: false
      default: "true"
    - name: scratchDir
      usage: Directory for holding temporary files and restic cache.
      required: false
      default: /kubestash-tmp
    volumeTemplate:
      - name: kubestash-tmp-volume
        usage: Holds temporary files and restic cache.
        source:
          emptyDir: {}
    volumeMounts:
      - name: kubestash-tmp-volume
        mountPath: /kubestash-tmp
  restoreTasks:
  - name: logical-backup-restore
    function: qdrant-restore
    driver: Restic
    executor: Job
    singleton: true
    parameters:
    - name: collections
      usage: Comma-separated list of collections to restore. If not provided, all collections will be restored.
      required: false
    - name: args
      usage: Arguments to be passed to the dump command.
      required: false
    - name: enableCache
      usage: Enable or disable caching. Disabling caching may impact backup performance.
      required: false
      default: "true"
    - name: scratchDir
      usage: Directory for holding temporary files and restic cache.
      required: false
      default: /kubestash-tmp
    volumeTemplate:
    - name: kubestash-tmp-volume
      usage: Holds temporary files and restic cache.
      source:
        emptyDir: {}
    volumeMounts:
    - name: kubestash-tmp-volume
      mountPath: /kubestash-tmp
  - name: manifest-restore
    function: kubedbmanifest-restore
    driver: Restic
    executor: Job
    singleton: true
    parameters:
    - name: enableCache
      usage: Enable or disable caching. Disabling caching may impact backup performance.
      required: false
      default: "true"
    - name: scratchDir
      usage: Directory for holding temporary files and restic cache.
      required: false
      default: /kubestash-tmp
    volumeTemplate:
    - name: kubestash-tmp-volume
      usage: Holds temporary files and restic cache.
      source:
        emptyDir: {}
    volumeMounts:
    - name: kubestash-tmp-volume
      mountPath: /kubestash-tmp