apiVersion: ops.kubedb.com/v1alpha1
kind: MySQLOpsRequest
metadata:
  name: my-scale-group-inplace
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: my-group
  verticalScaling:
    mode: InPlace
    mysql:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.1"
        limits:
          memory: "300Mi"
          cpu: "0.2"
