apiVersion: ops.kubedb.com/v1alpha1
kind: OracleOpsRequest
metadata:
  name: standalone-rotate-auth-user
  namespace: demo
spec:
  type: RotateAuth
  databaseRef:
    name: oracle-sa-sample
  authentication:
    secretRef:
      kind: Secret
      name: oracle-user-auth
  apply: IfReady
