apiVersion: ops.kubedb.com/v1alpha1
kind: OracleOpsRequest
metadata:
  name: dataguard-reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: oracle-dg-sample
  configuration:
    configSecret:
      name: oracle-custom
