apiVersion: kubedb.com/v1alpha2
kind: Neo4j
metadata:
  name: neo4j-pitr-source
  namespace: demo
  labels:
    archiver: neo4j-pitr
spec:
  version: "2026.06.0"
  replicas: 3
  archiver:
    ref:
      name: neo4j-pitr-archiver
      namespace: demo
  storageType: Durable
  storage:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  deletionPolicy: WipeOut
