apiVersion: storage.kubestash.com/v1alpha1
kind: RetentionPolicy
metadata:
  name: neo4j-pitr-retention
  namespace: demo
spec:
  maxRetentionPeriod: 2mo
  successfulSnapshots:
    last: 5
  failedSnapshots:
    last: 2
  usagePolicy:
    allowedNamespaces:
      from: Same
