apiVersion: v1
stringData:
  config.yaml: |
    log_level: DEBUG
    performance:
      max_search_threads: 8
      update_rate_limit: 100
kind: Secret
metadata:
  name: new-qdrant-configuration
  namespace: demo
type: Opaque
