apiVersion: v1
kind: Secret
metadata:
  name: neo4j-remote-alias-credentials
  namespace: demo
type: Opaque
stringData:
  credentials.yaml: |
    media.reviews:
      password: "<remote-database-password>"
    reviews-remote:
      password: "<remote-database-password>"
