apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  name: esops-rotate-license
  namespace: demo
spec:
  type: RotateLicense
  databaseRef:
    name: sample-es
  license:
    secretRef:
      name: sample-es-license-renewed
  timeout: 5m
  apply: IfReady
