# Optional sample for externally managed etcd.
# Requires the etcd-operator CRD: etcdclusters.operator.etcd.io
apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  name: etcdcluster-sample
  namespace: demo
spec:
  version: v3.5.21
  size: 3
  storageSpec:
    accessModes: ReadWriteOnce
    volumeSizeRequest: 1Gi
    volumeSizeLimit: 1Gi
    storageClassName: local-path
