apiVersion: ops.kubedb.com/v1alpha1
kind: DocumentDBOpsRequest
metadata:
  name: documentdb-sa-volume-expansion
  namespace: demo
spec:
  type: VolumeExpansion
  databaseRef:
    name: documentdb-sa-sample
  volumeExpansion:
    mode: Offline
    documentdb: 10Gi
