apiVersion: autoscaling.kubedb.com/v1alpha1
kind: QdrantAutoscaler
metadata:
  name: qdrant-as-storage
  namespace: demo
spec:
  databaseRef:
    name: qdrant-sample
  opsRequestOptions:
    timeout: 3m
    apply: IfReady
  storage:
    node:
      trigger: "On"
      expansionMode: Online
      usageThreshold: 70
      scalingThreshold: 50
      minAllowed: 2Gi
      maxAllowed: 50Gi