apiVersion: kubedb.com/v1
kind: MariaDB
metadata:
  name: mariadb-alert-demo
  namespace: alert-mariadb
spec:
  version: "11.5.2"
  replicas: 1
  storageType: Durable
  storage:
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
