apiVersion: ops.kubedb.com/v1alpha1
kind: QdrantOpsRequest
metadata:
  name: qdops-vol-exp
  namespace: demo
spec:
  type: VolumeExpansion
  databaseRef:
    name: qdrant-sample
  volumeExpansion:
    mode: "Offline"
    node: 3Gi
