apiVersion: ops.kubedb.com/v1alpha1
kind: WeaviateOpsRequest
metadata:
  name: weaviate-reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: weaviate-sample
  configuration:
    applyConfig:
      weaviate.yaml: |
        LOG_LEVEL: info