apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: qdrant-csi-snapshotter
spec:
  args:
  - volume-snapshot
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --wait-timeout=${waitTimeout:=300}
  image: almasood/qdrant-restic-plugin:20260428144910
