apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: qdrant-addon
spec:
  backupTasks:
  - name: volume-snapshot
    function: qdrant-csi-snapshotter
    driver: VolumeSnapshotter
    executor: Job
    singleton: true
    parameters:
      - name: volumeSnapshotClassName
        usage: The VolumeSnapshotClassName to be used by volumeSnapshot
        required: false
  restoreTasks:
  - name: volume-snapshot-restore
    function: qdrant-csi-snapshotter
    driver: VolumeSnapshotter
    executor: Job
    singleton: true
