apiVersion: ops.kubedb.com/v1alpha1
kind: EtcdOpsRequest
metadata:
  name: etcdops-update-issuer
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: etcd-cluster
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: etcd-new-issuer
