apiVersion: ops.kubedb.com/v1alpha1
kind: DocumentDBOpsRequest
metadata:
  name: documentdb-cls-reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: documentdb-cls-sample
  configuration:
    applyConfig:
      user.conf: |
        max_connections=250
