apiVersion: kubedb.com/v1alpha2
kind: ProxySQL
metadata:
  name: proxy-server
  namespace: demo
spec:
  version: "3.0.1-debian"
  replicas: 1
  syncUsers: true
  backend:
    name: mysql-server
  terminationPolicy: WipeOut