apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  name: zk-grafana-demo
  namespace: demo
spec:
  version: "3.8.3"
  replicas: 3
  deletionPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s
