apiVersion: courier.kubedb.com/v1alpha1
kind: PostgresMigration
metadata:
  name: postgres-migrate
  namespace: demo
spec:
  source:
    connectionInfo:
      appBinding:
        name: source-postgres
        namespace: demo
      dbName: shop
      maxConnections: 100
    pgDump:
      schemaOnly: true
    logicalReplication:
      copyData: true
      publication:
        name: "pub"
        mode: default
      subscription:
        name: "sub"
  target:
    connectionInfo:
      appBinding:
        name: target-postgres
        namespace: demo
      dbName: shop
      maxConnections: 100
