apiVersion: kubedb.com/v1alpha2
kind: RabbitMQ
metadata:
  name: rm-cluster
  namespace: demo
spec:
  version: "4.2.4"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  configuration:
    secretName: rabbit-custom-config
