apiVersion: ops.kubedb.com/v1alpha1
kind: Neo4jOpsRequest
metadata:
  name: neo4j-reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: neo4j-test
  configuration:
    applyConfig:
      neo4j.conf: |
        dbms.memory.pagecache.size=512M
        dbms.memory.heap.initial_size=512M
        dbms.memory.heap.max_size=512M