apiVersion: ops.kubedb.com/v1alpha1
kind: IgniteOpsRequest
metadata:
  name: igops-rotate-auth-user
  namespace: demo
spec:
  type: RotateAuth
  databaseRef:
    name: ignite-quickstart
  authentication:
    secretRef:
      kind: Secret
      name: ignite-quickstart-auth-user
  timeout: 5m
  apply: IfReady