apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: pg-update
  namespace: demo
spec:
  type: UpdateVersion
  updateVersion:
    targetVersion: "18.3"
  databaseRef:
    name: pg
