apiVersion: ops.kubedb.com/v1alpha1
kind: ProxySQLOpsRequest
metadata:
  name: proxyops-rotate-auth-generated
  namespace: demo
spec:
  type: RotateAuth
  proxyRef:
    name: proxy-server
  timeout: 5m
  apply: IfReady
