apiVersion: kubedb.com/v1
kind: ProxySQL
metadata:
  name: mariadb-proxy
  namespace: demo
spec:
  version: "3.0.1-debian"
  replicas: 3
  syncUsers: true
  backend:
    name: mariadb-galera
  deletionPolicy: WipeOut