apiVersion: v1
stringData:
  conf.yaml: |-
    ---
    authentication:
      anonymous_access:
        enabled: true
      oidc:
        enabled: false
    authorization:
      admin_list:
        enabled: false
      rbac:
        enabled: false

    query_defaults:
      limit: 400
    debug: false
kind: Secret
metadata:
  name: weaviate-custom-config
  namespace: demo
  labels:
    app.kubernetes.io/name: weaviates.kubedb.com  
    app.kubernetes.io/instance: weaviate-sample