apiVersion: kubedb.com/v1
kind: ProxySQL
metadata:
  name: builtin-prom-proxysql
  namespace: demo
spec:
  version: "3.0.1-debian"
  replicas: 1
  backend:
    name: my-group
  monitor:
    agent: prometheus.io/builtin
    prometheus:
      exporter:
        port: 42004
