apiVersion: kubedb.com/v1
kind: ProxySQL
metadata:
  name: proxysql-pvt-reg
  namespace: demo
spec:
  version: "3.0.1-debian"
  replicas: 1
  backend:
    name: my-group
  podTemplate:
    spec:
      imagePullSecrets:
      - name: myregistrykey