apiVersion: kubedb.com/v1alpha2
kind: Etcd
metadata:
  name: etcd-recommendation
  namespace: demo
spec:
  version: "3.6.4"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  authSecret:
    kind: Secret
    name: etcd-recommendation-auth
    rotateAfter: 720h
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: Issuer
      name: etcd-ca-issuer
    certificates:
      - alias: server
        duration: 2160h
      - alias: client
        duration: 2160h
      - alias: peer
        duration: 2160h
  deletionPolicy: WipeOut
