apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mgo-custom-config
  namespace: demo
spec:
  version: "8.0.17"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  configuration:
    secretName: mg-configuration
