apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg-standalone
  namespace: demo
spec:
  version: "8.0.17"
  storageType: Durable
  storage:
    storageClassName: topolvm-provisioner
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
