apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg-sharding
  namespace: demo
spec:
  version: "8.0.17"
  shardTopology:
    configServer:
      replicas: 3
      configuration:
        secretName: mg-custom-config
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      replicas: 2
      configuration:
        secretName: mg-custom-config
    shard:
      replicas: 3
      shards: 2
      configuration:
        secretName: mg-custom-config
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
